# fly.toml app configuration file generated for helpmepack on 2023-07-03T12:33:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "helpmepack"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
