name: Deploy
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  deploy:
    name: Deploy app to Production on Fly.io
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
